---
# Rule 1.2.2 must be applied before rules 1.2.1 and 1.2.4
- name: "1.2.2 | L1 | Ensure 'Account lockout threshold' is set to '5 or fewer invalid logon attempt(s), but not 0'"
  when:
    - w2022cis_rule_1_2_2_enabled
  community.windows.win_security_policy:
    section: System Access
    key: LockoutBadCount
    value: "{{ w2022cis_lockout_bad_logon_count }}"

- name: "1.2.1 | L1 | Ensure 'Account lockout duration' is set to '15 or more minute(s)'"
  when:
    - w2022cis_rule_1_2_1_enabled
  community.windows.win_security_policy:
    section: System Access
    key: LockoutDuration
    value: "{{ w2022cis_lockout_duration_in_minutes }}"
  ignore_errors: true
  tags:
    - always
    - skip_ansible_lint
  # Ignore errors in case the lockout and reset duration must be set in the opposite order

- name: "1.2.3 | L1 | Ensure 'Allow Administrator account lockout' is set to 'Enabled'"
  when:
    - w2022cis_rule_1_2_3_enabled
    - _w2022cis_standalone_or_member_server
  community.windows.win_security_policy:
    section: System Access
    key: AllowAdministratorLockout
    value: '1'

- name: "1.2.4 | L1 | Ensure 'Reset account lockout counter after' is set to '15 or more minute(s)'"
  when:
    - w2022cis_rule_1_2_4_enabled
  community.windows.win_security_policy:
    section: System Access
    key: ResetLockoutCount
    value: "{{ w2022cis_lockout_reset_time_in_minutes }}"

- name: "1.2.1 | L1 | Ensure 'Account lockout duration' is set to '15 or more minute(s)'"
  when:
    - w2022cis_rule_1_2_1_enabled
  community.windows.win_security_policy:
    section: System Access
    key: LockoutDuration
    value: "{{ w2022cis_lockout_duration_in_minutes }}"
