---
- name: "18.1.1.1 | L1 | Ensure 'Prevent enabling lock screen camera' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_1_1_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Personalization
    name: NoLockScreenCamera
    data: 1
    type: dword

- name: "18.1.1.2 | L1 | Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_1_1_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Personalization
    name: NoLockScreenSlideshow
    data: 1
    type: dword

- name: "18.1.2.2 | L1 | Ensure 'Allow users to enable online speech recognition services' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_1_2_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\InputPersonalization
    name: "AllowInputPersonalization"
    data: "0"
    type: dword

- name: "18.1.3 | L2 | Ensure 'Allow Online Tips' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_1_3_enabled
    - w2022cis_rule_18_1_3_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: AllowOnlineTips
    data: 0
    type: dword
