---
- name: "2.3.1.1 | L1 | Ensure 'Accounts: Block Microsoft accounts' is set to 'Users can't add or log on with Microsoft accounts'"
  when:
    - w2022cis_rule_2_3_1_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
    name: NoConnectedUser
    data: 3
    type: dword

- name: "2.3.1.2 | L1 | Ensure 'Accounts: Guest account status' is set to 'Disabled' (MS only)"
  when:
    - w2022cis_rule_2_3_1_2_enabled
    - _w2022cis_standalone_or_member_server
  community.windows.win_security_policy:
    section: System Access
    key: EnableGuestAccount
    value: 0

- name: "2.3.1.3 | L1 | Ensure 'Accounts: Limit local account use of blank passwords to console logon only' is set to 'Enabled'"
  when:
    - w2022cis_rule_2_3_1_3_enabled
  ansible.windows.win_regedit:
    path: HKLM:\System\Currentcontrolset\Control\Lsa
    name: LimitBlankPasswordUse
    data: 1
    type: dword

- name: "2.3.1.4 | L1 | Configure 'Accounts: Rename administrator account'"
  when:
    - w2022cis_rule_2_3_1_4_enabled
  community.windows.win_security_policy:
    section: System Access
    key: newadministratorname
    value: "{{ w2022cis_admin_username }}"

- name: "2.3.1.5 | L1 | Configure 'Accounts: Rename guest account'"
  when:
    - w2022cis_rule_2_3_1_5_enabled
  community.windows.win_security_policy:
    section: System Access
    key: NewGuestName
    value: "{{ w2022cis_guest_username }}"
