---
- name: "17.5.1 | L1 | Ensure 'Audit Account Lockout' is set to include 'Failure'"
  when:
    - w2022cis_rule_17_5_1_enabled
  block:
    - name: "17.5.1 | L1 | Ensure 'Audit Account Lockout' is set to include 'Failure'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"Account Lockout" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_5_1_audit

    - name: "17.5.1 | L1 | Ensure 'Audit Account Lockout' is set to include 'Failure'"
      when:
        - "'Failure' not in _w2022cis_rule_17_5_1_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"Account Lockout" /failure:enable

- name: "17.5.2 | L1 | Ensure 'Audit Group Membership' is set to include 'Success'"
  when:
    - w2022cis_rule_17_5_2_enabled
  block:
    - name: "17.5.2 | L1 | Ensure 'Audit Group Membership' is set to include 'Success'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"Group Membership" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_5_2_audit

    - name: "17.5.2 | L1 | Ensure 'Audit Group Membership' is set to include 'Success'"
      when:
        - "'Success' not in _w2022cis_rule_17_5_2_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"Group Membership" /success:enable

- name: "17.5.3 | L1 | Ensure 'Audit Logoff' is set to include 'Success'"
  when:
    - w2022cis_rule_17_5_3_enabled
  block:
    - name: "17.5.3 | L1 | Ensure 'Audit Logoff' is set to include 'Success'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"Logoff" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_5_3_audit

    - name: "17.5.3 | L1 | Ensure 'Audit Logoff' is set to include 'Success'"
      when:
        - "'Success' not in _w2022cis_rule_17_5_3_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"Logoff" /success:enable

- name: "17.5.4 | L1 | Ensure 'Audit Logon' is set to 'Success and Failure'"
  when:
    - w2022cis_rule_17_5_4_enabled
  block:
    - name: "17.5.4 | L1 | Ensure 'Audit Logon' is set to 'Success and Failure'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"Logon" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_5_4_audit

    - name: "17.5.4 | L1 | Ensure 'Audit Logon' is set to 'Success and Failure' | Success"
      when:
        - "'Success' not in _w2022cis_rule_17_5_4_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"Logon" /success:enable

    - name: "17.5.4 | L1 | Ensure 'Audit Logon' is set to 'Success and Failure' | Failure"
      when:
        - "'Failure' not in _w2022cis_rule_17_5_4_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"Logon" /failure:enable

- name: "17.5.5 | L1 | Ensure 'Audit Other Logon/Logoff Events' is set to 'Success and Failure'"
  when:
    - w2022cis_rule_17_5_5_enabled
  block:
    - name: "17.5.5 | L1 | Ensure 'Audit Other Logon/Logoff Events' is set to 'Success and Failure'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"Other Logon/Logoff Events" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_5_5_audit

    - name: "17.5.5 | L1 | Ensure 'Audit Other Logon/Logoff Events' is set to 'Success and Failure' | Success"
      when:
        - "'Success' not in _w2022cis_rule_17_5_5_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"Other Logon/Logoff Events" /success:enable

    - name: "17.5.5 | L1 | Ensure 'Audit Other Logon/Logoff Events' is set to 'Success and Failure' | Failure"
      when:
        - "'Failure' not in _w2022cis_rule_17_5_5_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"Other Logon/Logoff Events" /failure:enable

- name: "17.5.6 | L1 | Ensure 'Audit Special Logon' is set to include 'Success'"
  when:
    - w2022cis_rule_17_5_6_enabled
  block:
    - name: "17.5.6 | L1 | Ensure 'Audit Special Logon' is set to include 'Success'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"Special Logon" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_5_6_audit

    - name: "17.5.6 | L1 | Ensure 'Audit Special Logon' is set to include 'Success'"
      when:
        - "'Success' not in _w2022cis_rule_17_5_6_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"Special Logon" /success:enable
