---
- name: "18.10.58.1 | L1 | Ensure 'Prevent downloading of enclosures' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_58_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Internet Explorer\Feeds
    name: DisableEnclosureDownload
    data: 1
    type: dword
