---
- name: "18.10.42.1 | L1 | Ensure 'Block all consumer Microsoft account user authentication' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_42_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\MicrosoftAccount
    name: DisableUserAuth
    data: 1
    type: dword
