---
- name: "18.10.57.2.2 | L1 | Ensure 'Do not allow passwords to be saved' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_57_2_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: DisablePasswordSaving
    data: 1
    type: dword

- name: "18.10.57.3.2.1 | L2 | Ensure 'Restrict Remote Desktop Services users to a single Remote Desktop Services session' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_57_3_2_1_enabled
    - w2022cis_rule_18_10_57_3_2_1_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: fSingleSessionPerUser
    data: 1
    type: dword

- name: "18.10.57.3.3.1 | L2 | Ensure 'Do not allow COM port redirection' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_57_3_3_1_enabled
    - w2022cis_rule_18_10_57_3_3_1_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: fDisableCcm
    data: 1
    type: dword

- name: "18.10.57.3.3.2 | L1 | Ensure 'Do not allow drive redirection' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_57_3_3_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: fDisableCdm
    data: 1
    type: dword

- name: "18.10.57.3.3.3 | L2 | Ensure 'Do not allow LPT port redirection' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_57_3_3_3_enabled
    - w2022cis_rule_18_10_57_3_3_3_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: fDisableLPT
    data: 1
    type: dword

- name: "18.10.57.3.3.4 | L2 | Ensure 'Do not allow supported Plug and Play device redirection' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_57_3_3_4_enabled
    - w2022cis_rule_18_10_57_3_3_4_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: fDisablePNPRedir
    data: 1
    type: dword

- name: "18.10.57.3.9.1 | L1 | Ensure 'Always prompt for password upon connection' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_57_3_9_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: fPromptForPassword
    data: 1
    type: dword

- name: "18.10.57.3.9.2 | L1 | Ensure 'Require secure RPC communication' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_57_3_9_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: fEncryptRPCTraffic
    data: 1
    type: dword

- name: "18.10.57.3.9.3 | L1 | Ensure 'Require use of specific security layer for remote (RDP) connections' is set to 'Enabled: SSL'"
  when:
    - w2022cis_rule_18_10_57_3_9_3_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: SecurityLayer
    data: 2
    type: dword

- name: "18.10.57.3.9.4 | L1 | Ensure 'Require user authentication for remote connections by using Network Level Authentication' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_57_3_9_4_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: UserAuthentication
    data: 1
    type: dword

- name: "18.10.57.3.9.5 | L1 | Ensure 'Set client connection encryption level' is set to 'Enabled: High Level'"
  when:
    - w2022cis_rule_18_10_57_3_9_5_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: MinEncryptionLevel
    data: 3
    type: dword

- name: "18.10.57.3.10.1 | L2 | Ensure 'Set time limit for active but idle Remote Desktop Services sessions' is set to 'Enabled: 15 minutes or less, but not Never (0)'"
  when:
    - w2022cis_rule_18_10_57_3_10_1_enabled
    - w2022cis_rule_18_10_57_3_10_1_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: MaxIdleTime
    data: 900000
    type: dword

- name: "18.10.57.3.10.2 | L2 |Ensure 'Set time limit for disconnected sessions' is set to 'Enabled: 1 minute'"
  when:
    - w2022cis_rule_18_10_57_3_10_2_enabled
    - w2022cis_rule_18_10_57_3_10_2_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: MaxDisconnectionTime
    data: 60000
    type: dword

- name: "18.10.57.3.11.1 | L1 | Ensure 'Do not delete temp folders upon exit' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_10_57_3_11_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: DeleteTempDirsOnExit
    data: 1
    type: dword

- name: "18.10.57.3.11.2 | L1 | Ensure 'Do not use temporary folders per session' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_10_57_3_11_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: PerSessionTempDir
    data: 1
    type: dword
