---
- name: "18.10.81.1 | L1 | Ensure 'Allow user control over installs' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_10_81_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Installer
    name: EnableUserControl
    data: 0
    type: dword

- name: "18.10.81.2 | L1 | Ensure 'Always install with elevated privileges' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_10_81_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Installer
    name: AlwaysInstallElevated
    data: 0
    type: dword

- name: "18.10.81.3 | L2 | Ensure 'Prevent Internet Explorer security prompt for Windows Installer scripts' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_10_81_3_enabled
    - w2022cis_rule_18_10_81_3_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Installer
    name: SafeForScripting
    data: 0
    type: dword
