---
- name: "18.10.43.5.1 | L1 | Ensure 'Configure local setting override for reporting to Microsoft MAPS' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_10_43_5_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Spynet
    name: LocalSettingOverrideSpynetReporting
    data: 0
    type: dword

- name: "18.10.43.5.2 | L2 | Ensure 'Join Microsoft MAPS' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_10_43_5_2_enabled
    - w2022cis_rule_18_10_43_5_2_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Spynet
    name: SpynetReporting
    data: 0
    type: dword
    
- name: "18.10.43.6.1.1 | L1 | Ensure 'Configure Attack Surface Reduction rules' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_43_6_1_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR
    name: ExploitGuard_ASR_Rules
    data: 1
    type: dword

- name: "18.10.43.6.1.2 | L1 | Ensure 'Configure Attack Surface Reduction rules: Set the state for each ASR rule' is configured"
  loop:
    - 26190899-1602-49e8-8b27-eb1d0a1ce869
    - 3b576869-a4ec-4529-8536-b80a7769e899
    - 56a863a9-875e-4185-98a7-b882c64b5ce5
    - 5beb7efe-fd9a-4556-801d-275e5ffc04cc
    - 75668c1f-73b5-4cf0-bb93-3ecf5cb7cc84
    - 7674ba52-37eb-4a4f-a9a1-f0f9a1619a2c
    - 92e97fa1-2edf-4476-bdd6-9dd0b4dddc7b
    - 9e6c4e1f-7d60-472f-ba1a-a39ef669e4b2
    - b2b3f03d-6a65-4f7b-a9c7-1c7ef74a9ba4
    - be9ba2d9-53ea-4cdc-84e5-9b1eeee46550
    - d3e037e1-3eb8-44c8-a917-57927947596d
    - d4f940ab-401b-4efc-aadc-ad5f3c50688a
    - e6db77e5-3df2-4cf1-b95a-636979351e5b
  when:
    - w2022cis_rule_18_10_43_6_1_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
    name: "{{ item }}"
    data: 1
    type: string

- name: "18.10.43.6.3.1 | L1 | Ensure 'Prevent users and apps from accessing dangerous websites' is set to 'Enabled: Block'"
  when:
    - w2022cis_rule_18_10_43_6_3_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\Network Protection
    name: EnableNetworkProtection
    data: 1
    type: dword

- name: "18.10.43.7.1 | L2 | Ensure 'Enable file hash computation feature' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_43_7_1_enabled
    - w2022cis_rule_18_10_43_7_1_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\MpEngine
    name: EnableFileHashComputation
    data: 1
    type: dword

- name: "18.10.43.10.1 | L1 | Ensure 'Scan all downloaded files and attachments' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_43_10_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection
    name: DisableIOAVProtection
    data: 0
    type: dword

- name: "18.10.43.10.2 | L1 | Ensure 'Turn off real-time protection' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_10_43_10_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection
    name: DisableRealtimeMonitoring
    data: 0
    type: dword

- name: "18.10.43.10.3 | L1 | Ensure 'Turn on behavior monitoring' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_43_10_3_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection
    name: DisableBehaviorMonitoring
    data: 0
    type: dword

- name: "18.10.43.10.4 | L1 | Ensure 'Turn on script scanning' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_43_10_4_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection
    name: DisableScriptScanning
    data: 0
    type: dword

- name: "18.10.43.12.1 | L2 | Ensure 'Configure Watson events' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_10_43_12_1_enabled
    - w2022cis_rule_18_10_43_12_1_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Reporting
    name: DisableGenericRePorts
    data: 1
    type: dword

- name: "18.10.43.13.1 | L1 | Ensure 'Scan removable drives' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_43_13_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Scan
    name: DisableRemovableDriveScanning
    data: 0
    type: dword

- name: "18.10.43.13.2 | L1 | Ensure 'Turn on e-mail scanning' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_43_13_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Scan
    name: DisableEmailScanning
    data: 0
    type: dword

- name: "18.10.43.16 | L1 | Ensure 'Configure detection for potentially unwanted applications' is set to 'Enabled: Block'"
  when:
    - w2022cis_rule_18_10_43_16_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender
    name: PUAProtection
    data: 1
    type: dword

- name: "18.10.43.17 | L1 | Ensure 'Turn off Microsoft Defender AntiVirus' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_10_43_17_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender
    name: DisableAntiSpyware
    data: 0
    type: dword
