---
- name: "18.10.8.1.1 | L1 | Ensure 'Configure enhanced anti-spoofing' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_8_1_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Biometrics\Facialfeatures
    name: EnhancedAntiSpoofing
    data: 1
    type: dword
