---
- name: "18.10.14.1 | L1 | Ensure 'Do not display the password reveal button' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_14_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Credui
    name: DisablePasswordReveal
    data: 1
    type: dword

- name: "18.10.14.2 | L1 | Ensure 'Enumerate administrator accounts on elevation' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_10_14_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Credui
    name: EnumerateAdministrators
    data: 0
    type: dword
