---
- name: "18.10.87.1 | L1 | Ensure 'Turn on PowerShell Script Block Logging' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_87_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Powershell\Scriptblocklogging
    name: EnableScriptBlockLogging
    data: 1
    type: dword

- name: "18.10.87.2 | L1 | Ensure 'Turn on PowerShell Transcription' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_10_87_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Powershell\Transcription
    name: EnableTranscripting
    data: 0
    type: dword
