---
- name: "18.10.92.2.1 | L1 | Ensure 'Prevent users from modifying settings' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_92_2_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender Security Center\App and Browser protection
    name: DisallowExploitProtectionOverride
    data: 1
    type: dword
