---
- name: "19.6.6.1.1 | L2 | Ensure 'Turn off Help Experience Improvement Program' is set to 'Enabled'"
  loop: "{{ _w2022cis_user_hives.sub_keys }}"
  when:
    - w2022cis_rule_19_6_6_1_1_enabled
    - w2022cis_rule_19_6_6_1_1_force or _w2022cis_level2
    - "'Classes' not in item"
  ansible.windows.win_regedit:
    path: "HKU:\\{{ item }}\\Software\\Policies\\Microsoft\\Assistance\\Client\\1.0"
    name: NoImplicitFeedback
    data: 1
    type: dword
